version: '2.1'
services:
  nicom_crawler:
    build: .
    volumes:
      - .:/app
    command: [
      'crawl',
      'nicom',
    ]
  thomann:
    extends: nicom_crawler
    command: [
      'crawl',
      'thomann',
    ]
  justmusic:
    extends: nicom_crawler
    command: [
      'crawl',
      'justmusic',
    ]
  gear4music:
    extends: nicom_crawler
    command: [
      'crawl',
      'gear4music',
    ]
  musikhauskorn:
    extends: nicom_crawler
    command: [
      'crawl',
      'musikhauskorn',
    ]
